remote_theme: pmarsceill/just-the-docs

title: "This is the Title"
description: "This is the description in the yml file."

search_enabled: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"